name = str(input("Full Name: ")).strip()
print("Name in Upper case: {}".format(name.upper()))
print("Name in Lower case: {}".format(name.lower()))
print(len(name) - name.count(" "))
print(name.find(" "))